import { Surah, Juz } from '../types/quran.types';

// Complete list of 114 Surahs with metadata
export const SURAHS: Surah[] = [
    { id: 1, name: 'الفاتحة', transliteration: 'Al-Fatihah', translation: 'The Opening', revelation: 'Meccan', numberOfAyahs: 7, juz: [1], page: 1 },
    { id: 2, name: 'البقرة', transliteration: 'Al-Baqarah', translation: 'The Cow', revelation: 'Medinan', numberOfAyahs: 286, juz: [1, 2, 3], page: 2 },
    { id: 3, name: 'آل عمران', transliteration: 'Ali \'Imran', translation: 'Family of Imran', revelation: 'Medinan', numberOfAyahs: 200, juz: [3, 4], page: 50 },
    { id: 4, name: 'النساء', transliteration: 'An-Nisa', translation: 'The Women', revelation: 'Medinan', numberOfAyahs: 176, juz: [4, 5, 6], page: 77 },
    { id: 5, name: 'المائدة', transliteration: 'Al-Ma\'idah', translation: 'The Table Spread', revelation: 'Medinan', numberOfAyahs: 120, juz: [6, 7], page: 106 },
    { id: 6, name: 'الأنعام', transliteration: 'Al-An\'am', translation: 'The Cattle', revelation: 'Meccan', numberOfAyahs: 165, juz: [7, 8], page: 128 },
    { id: 7, name: 'الأعراف', transliteration: 'Al-A\'raf', translation: 'The Heights', revelation: 'Meccan', numberOfAyahs: 206, juz: [8, 9], page: 151 },
    { id: 8, name: 'الأنفال', transliteration: 'Al-Anfal', translation: 'The Spoils of War', revelation: 'Medinan', numberOfAyahs: 75, juz: [9, 10], page: 177 },
    { id: 9, name: 'التوبة', transliteration: 'At-Tawbah', translation: 'The Repentance', revelation: 'Medinan', numberOfAyahs: 129, juz: [10, 11], page: 187 },
    { id: 10, name: 'يونس', transliteration: 'Yunus', translation: 'Jonah', revelation: 'Meccan', numberOfAyahs: 109, juz: [11], page: 208 },
    { id: 11, name: 'هود', transliteration: 'Hud', translation: 'Hud', revelation: 'Meccan', numberOfAyahs: 123, juz: [11, 12], page: 221 },
    { id: 12, name: 'يوسف', transliteration: 'Yusuf', translation: 'Joseph', revelation: 'Meccan', numberOfAyahs: 111, juz: [12, 13], page: 235 },
    { id: 13, name: 'الرعد', transliteration: 'Ar-Ra\'d', translation: 'The Thunder', revelation: 'Medinan', numberOfAyahs: 43, juz: [13], page: 249 },
    { id: 14, name: 'إبراهيم', transliteration: 'Ibrahim', translation: 'Abraham', revelation: 'Meccan', numberOfAyahs: 52, juz: [13], page: 255 },
    { id: 15, name: 'الحجر', transliteration: 'Al-Hijr', translation: 'The Rocky Tract', revelation: 'Meccan', numberOfAyahs: 99, juz: [14], page: 262 },
    { id: 16, name: 'النحل', transliteration: 'An-Nahl', translation: 'The Bee', revelation: 'Meccan', numberOfAyahs: 128, juz: [14], page: 267 },
    { id: 17, name: 'الإسراء', transliteration: 'Al-Isra', translation: 'The Night Journey', revelation: 'Meccan', numberOfAyahs: 111, juz: [15], page: 282 },
    { id: 18, name: 'الكهف', transliteration: 'Al-Kahf', translation: 'The Cave', revelation: 'Meccan', numberOfAyahs: 110, juz: [15, 16], page: 293 },
    { id: 19, name: 'مريم', transliteration: 'Maryam', translation: 'Mary', revelation: 'Meccan', numberOfAyahs: 98, juz: [16], page: 305 },
    { id: 20, name: 'طه', transliteration: 'Taha', translation: 'Ta-Ha', revelation: 'Meccan', numberOfAyahs: 135, juz: [16], page: 312 },
    { id: 21, name: 'الأنبياء', transliteration: 'Al-Anbiya', translation: 'The Prophets', revelation: 'Meccan', numberOfAyahs: 112, juz: [17], page: 322 },
    { id: 22, name: 'الحج', transliteration: 'Al-Hajj', translation: 'The Pilgrimage', revelation: 'Medinan', numberOfAyahs: 78, juz: [17], page: 332 },
    { id: 23, name: 'المؤمنون', transliteration: 'Al-Mu\'minun', translation: 'The Believers', revelation: 'Meccan', numberOfAyahs: 118, juz: [18], page: 342 },
    { id: 24, name: 'النور', transliteration: 'An-Nur', translation: 'The Light', revelation: 'Medinan', numberOfAyahs: 64, juz: [18], page: 350 },
    { id: 25, name: 'الفرقان', transliteration: 'Al-Furqan', translation: 'The Criterion', revelation: 'Meccan', numberOfAyahs: 77, juz: [18, 19], page: 359 },
    { id: 26, name: 'الشعراء', transliteration: 'Ash-Shu\'ara', translation: 'The Poets', revelation: 'Meccan', numberOfAyahs: 227, juz: [19], page: 367 },
    { id: 27, name: 'النمل', transliteration: 'An-Naml', translation: 'The Ant', revelation: 'Meccan', numberOfAyahs: 93, juz: [19, 20], page: 377 },
    { id: 28, name: 'القصص', transliteration: 'Al-Qasas', translation: 'The Stories', revelation: 'Meccan', numberOfAyahs: 88, juz: [20], page: 385 },
    { id: 29, name: 'العنكبوت', transliteration: 'Al-\'Ankabut', translation: 'The Spider', revelation: 'Meccan', numberOfAyahs: 69, juz: [20, 21], page: 396 },
    { id: 30, name: 'الروم', transliteration: 'Ar-Rum', translation: 'The Romans', revelation: 'Meccan', numberOfAyahs: 60, juz: [21], page: 404 },
    { id: 31, name: 'لقمان', transliteration: 'Luqman', translation: 'Luqman', revelation: 'Meccan', numberOfAyahs: 34, juz: [21], page: 411 },
    { id: 32, name: 'السجدة', transliteration: 'As-Sajdah', translation: 'The Prostration', revelation: 'Meccan', numberOfAyahs: 30, juz: [21], page: 415 },
    { id: 33, name: 'الأحزاب', transliteration: 'Al-Ahzab', translation: 'The Combined Forces', revelation: 'Medinan', numberOfAyahs: 73, juz: [21, 22], page: 418 },
    { id: 34, name: 'سبأ', transliteration: 'Saba', translation: 'Sheba', revelation: 'Meccan', numberOfAyahs: 54, juz: [22], page: 428 },
    { id: 35, name: 'فاطر', transliteration: 'Fatir', translation: 'Originator', revelation: 'Meccan', numberOfAyahs: 45, juz: [22], page: 434 },
    { id: 36, name: 'يس', transliteration: 'Ya-Sin', translation: 'Ya Sin', revelation: 'Meccan', numberOfAyahs: 83, juz: [22, 23], page: 440 },
    { id: 37, name: 'الصافات', transliteration: 'As-Saffat', translation: 'Those in Ranks', revelation: 'Meccan', numberOfAyahs: 182, juz: [23], page: 446 },
    { id: 38, name: 'ص', transliteration: 'Sad', translation: 'Sad', revelation: 'Meccan', numberOfAyahs: 88, juz: [23], page: 453 },
    { id: 39, name: 'الزمر', transliteration: 'Az-Zumar', translation: 'The Troops', revelation: 'Meccan', numberOfAyahs: 75, juz: [23, 24], page: 458 },
    { id: 40, name: 'غافر', transliteration: 'Ghafir', translation: 'The Forgiver', revelation: 'Meccan', numberOfAyahs: 85, juz: [24], page: 467 },
    { id: 41, name: 'فصلت', transliteration: 'Fussilat', translation: 'Explained in Detail', revelation: 'Meccan', numberOfAyahs: 54, juz: [24, 25], page: 477 },
    { id: 42, name: 'الشورى', transliteration: 'Ash-Shura', translation: 'The Consultation', revelation: 'Meccan', numberOfAyahs: 53, juz: [25], page: 483 },
    { id: 43, name: 'الزخرف', transliteration: 'Az-Zukhruf', translation: 'The Ornaments of Gold', revelation: 'Meccan', numberOfAyahs: 89, juz: [25], page: 489 },
    { id: 44, name: 'الدخان', transliteration: 'Ad-Dukhan', translation: 'The Smoke', revelation: 'Meccan', numberOfAyahs: 59, juz: [25], page: 496 },
    { id: 45, name: 'الجاثية', transliteration: 'Al-Jathiyah', translation: 'The Crouching', revelation: 'Meccan', numberOfAyahs: 37, juz: [25], page: 499 },
    { id: 46, name: 'الأحقاف', transliteration: 'Al-Ahqaf', translation: 'The Wind-Curved Sandhills', revelation: 'Meccan', numberOfAyahs: 35, juz: [26], page: 502 },
    { id: 47, name: 'محمد', transliteration: 'Muhammad', translation: 'Muhammad', revelation: 'Medinan', numberOfAyahs: 38, juz: [26], page: 507 },
    { id: 48, name: 'الفتح', transliteration: 'Al-Fath', translation: 'The Victory', revelation: 'Medinan', numberOfAyahs: 29, juz: [26], page: 511 },
    { id: 49, name: 'الحجرات', transliteration: 'Al-Hujurat', translation: 'The Rooms', revelation: 'Medinan', numberOfAyahs: 18, juz: [26], page: 515 },
    { id: 50, name: 'ق', transliteration: 'Qaf', translation: 'Qaf', revelation: 'Meccan', numberOfAyahs: 45, juz: [26], page: 518 },
    { id: 51, name: 'الذاريات', transliteration: 'Adh-Dhariyat', translation: 'The Winnowing Winds', revelation: 'Meccan', numberOfAyahs: 60, juz: [26, 27], page: 520 },
    { id: 52, name: 'الطور', transliteration: 'At-Tur', translation: 'The Mount', revelation: 'Meccan', numberOfAyahs: 49, juz: [27], page: 523 },
    { id: 53, name: 'النجم', transliteration: 'An-Najm', translation: 'The Star', revelation: 'Meccan', numberOfAyahs: 62, juz: [27], page: 526 },
    { id: 54, name: 'القمر', transliteration: 'Al-Qamar', translation: 'The Moon', revelation: 'Meccan', numberOfAyahs: 55, juz: [27], page: 528 },
    { id: 55, name: 'الرحمن', transliteration: 'Ar-Rahman', translation: 'The Beneficent', revelation: 'Medinan', numberOfAyahs: 78, juz: [27], page: 531 },
    { id: 56, name: 'الواقعة', transliteration: 'Al-Waqi\'ah', translation: 'The Inevitable', revelation: 'Meccan', numberOfAyahs: 96, juz: [27], page: 534 },
    { id: 57, name: 'الحديد', transliteration: 'Al-Hadid', translation: 'The Iron', revelation: 'Medinan', numberOfAyahs: 29, juz: [27], page: 537 },
    { id: 58, name: 'المجادلة', transliteration: 'Al-Mujadila', translation: 'The Pleading Woman', revelation: 'Medinan', numberOfAyahs: 22, juz: [28], page: 542 },
    { id: 59, name: 'الحشر', transliteration: 'Al-Hashr', translation: 'The Exile', revelation: 'Medinan', numberOfAyahs: 24, juz: [28], page: 545 },
    { id: 60, name: 'الممتحنة', transliteration: 'Al-Mumtahanah', translation: 'She that is to be examined', revelation: 'Medinan', numberOfAyahs: 13, juz: [28], page: 549 },
    { id: 61, name: 'الصف', transliteration: 'As-Saf', translation: 'The Ranks', revelation: 'Medinan', numberOfAyahs: 14, juz: [28], page: 551 },
    { id: 62, name: 'الجمعة', transliteration: 'Al-Jumu\'ah', translation: 'The Congregation', revelation: 'Medinan', numberOfAyahs: 11, juz: [28], page: 553 },
    { id: 63, name: 'المنافقون', transliteration: 'Al-Munafiqun', translation: 'The Hypocrites', revelation: 'Medinan', numberOfAyahs: 11, juz: [28], page: 554 },
    { id: 64, name: 'التغابن', transliteration: 'At-Taghabun', translation: 'The Mutual Disillusion', revelation: 'Medinan', numberOfAyahs: 18, juz: [28], page: 556 },
    { id: 65, name: 'الطلاق', transliteration: 'At-Talaq', translation: 'The Divorce', revelation: 'Medinan', numberOfAyahs: 12, juz: [28], page: 558 },
    { id: 66, name: 'التحريم', transliteration: 'At-Tahrim', translation: 'The Prohibition', revelation: 'Medinan', numberOfAyahs: 12, juz: [28], page: 560 },
    { id: 67, name: 'الملك', transliteration: 'Al-Mulk', translation: 'The Sovereignty', revelation: 'Meccan', numberOfAyahs: 30, juz: [29], page: 562 },
    { id: 68, name: 'القلم', transliteration: 'Al-Qalam', translation: 'The Pen', revelation: 'Meccan', numberOfAyahs: 52, juz: [29], page: 564 },
    { id: 69, name: 'الحاقة', transliteration: 'Al-Haqqah', translation: 'The Reality', revelation: 'Meccan', numberOfAyahs: 52, juz: [29], page: 566 },
    { id: 70, name: 'المعارج', transliteration: 'Al-Ma\'arij', translation: 'The Ascending Stairways', revelation: 'Meccan', numberOfAyahs: 44, juz: [29], page: 568 },
    { id: 71, name: 'نوح', transliteration: 'Nuh', translation: 'Noah', revelation: 'Meccan', numberOfAyahs: 28, juz: [29], page: 570 },
    { id: 72, name: 'الجن', transliteration: 'Al-Jinn', translation: 'The Jinn', revelation: 'Meccan', numberOfAyahs: 28, juz: [29], page: 572 },
    { id: 73, name: 'المزمل', transliteration: 'Al-Muzzammil', translation: 'The Enshrouded One', revelation: 'Meccan', numberOfAyahs: 20, juz: [29], page: 574 },
    { id: 74, name: 'المدثر', transliteration: 'Al-Muddathir', translation: 'The Cloaked One', revelation: 'Meccan', numberOfAyahs: 56, juz: [29], page: 575 },
    { id: 75, name: 'القيامة', transliteration: 'Al-Qiyamah', translation: 'The Resurrection', revelation: 'Meccan', numberOfAyahs: 40, juz: [29], page: 577 },
    { id: 76, name: 'الإنسان', transliteration: 'Al-Insan', translation: 'The Man', revelation: 'Medinan', numberOfAyahs: 31, juz: [29], page: 578 },
    { id: 77, name: 'المرسلات', transliteration: 'Al-Mursalat', translation: 'The Emissaries', revelation: 'Meccan', numberOfAyahs: 50, juz: [29], page: 580 },
    { id: 78, name: 'النبأ', transliteration: 'An-Naba', translation: 'The Tidings', revelation: 'Meccan', numberOfAyahs: 40, juz: [30], page: 582 },
    { id: 79, name: 'النازعات', transliteration: 'An-Nazi\'at', translation: 'Those who drag forth', revelation: 'Meccan', numberOfAyahs: 46, juz: [30], page: 583 },
    { id: 80, name: 'عبس', transliteration: 'Abasa', translation: 'He Frowned', revelation: 'Meccan', numberOfAyahs: 42, juz: [30], page: 585 },
    { id: 81, name: 'التكوير', transliteration: 'At-Takwir', translation: 'The Overthrowing', revelation: 'Meccan', numberOfAyahs: 29, juz: [30], page: 586 },
    { id: 82, name: 'الانفطار', transliteration: 'Al-Infitar', translation: 'The Cleaving', revelation: 'Meccan', numberOfAyahs: 19, juz: [30], page: 587 },
    { id: 83, name: 'المطففين', transliteration: 'Al-Mutaffifin', translation: 'The Defrauding', revelation: 'Meccan', numberOfAyahs: 36, juz: [30], page: 587 },
    { id: 84, name: 'الانشقاق', transliteration: 'Al-Inshiqaq', translation: 'The Sundering', revelation: 'Meccan', numberOfAyahs: 25, juz: [30], page: 589 },
    { id: 85, name: 'البروج', transliteration: 'Al-Buruj', translation: 'The Mansions of the Stars', revelation: 'Meccan', numberOfAyahs: 22, juz: [30], page: 590 },
    { id: 86, name: 'الطارق', transliteration: 'At-Tariq', translation: 'The Nightcomer', revelation: 'Meccan', numberOfAyahs: 17, juz: [30], page: 591 },
    { id: 87, name: 'الأعلى', transliteration: 'Al-A\'la', translation: 'The Most High', revelation: 'Meccan', numberOfAyahs: 19, juz: [30], page: 591 },
    { id: 88, name: 'الغاشية', transliteration: 'Al-Ghashiyah', translation: 'The Overwhelming', revelation: 'Meccan', numberOfAyahs: 26, juz: [30], page: 592 },
    { id: 89, name: 'الفجر', transliteration: 'Al-Fajr', translation: 'The Dawn', revelation: 'Meccan', numberOfAyahs: 30, juz: [30], page: 593 },
    { id: 90, name: 'البلد', transliteration: 'Al-Balad', translation: 'The City', revelation: 'Meccan', numberOfAyahs: 20, juz: [30], page: 594 },
    { id: 91, name: 'الشمس', transliteration: 'Ash-Shams', translation: 'The Sun', revelation: 'Meccan', numberOfAyahs: 15, juz: [30], page: 595 },
    { id: 92, name: 'الليل', transliteration: 'Al-Layl', translation: 'The Night', revelation: 'Meccan', numberOfAyahs: 21, juz: [30], page: 595 },
    { id: 93, name: 'الضحى', transliteration: 'Ad-Duhaa', translation: 'The Morning Hours', revelation: 'Meccan', numberOfAyahs: 11, juz: [30], page: 596 },
    { id: 94, name: 'الشرح', transliteration: 'Ash-Sharh', translation: 'The Relief', revelation: 'Meccan', numberOfAyahs: 8, juz: [30], page: 596 },
    { id: 95, name: 'التين', transliteration: 'At-Tin', translation: 'The Fig', revelation: 'Meccan', numberOfAyahs: 8, juz: [30], page: 597 },
    { id: 96, name: 'العلق', transliteration: 'Al-\'Alaq', translation: 'The Clot', revelation: 'Meccan', numberOfAyahs: 19, juz: [30], page: 597 },
    { id: 97, name: 'القدر', transliteration: 'Al-Qadr', translation: 'The Power', revelation: 'Meccan', numberOfAyahs: 5, juz: [30], page: 598 },
    { id: 98, name: 'البينة', transliteration: 'Al-Bayyinah', translation: 'The Clear Proof', revelation: 'Medinan', numberOfAyahs: 8, juz: [30], page: 598 },
    { id: 99, name: 'الزلزلة', transliteration: 'Az-Zalzalah', translation: 'The Earthquake', revelation: 'Medinan', numberOfAyahs: 8, juz: [30], page: 599 },
    { id: 100, name: 'العاديات', transliteration: 'Al-\'Adiyat', translation: 'The Courser', revelation: 'Meccan', numberOfAyahs: 11, juz: [30], page: 599 },
    { id: 101, name: 'القارعة', transliteration: 'Al-Qari\'ah', translation: 'The Calamity', revelation: 'Meccan', numberOfAyahs: 11, juz: [30], page: 600 },
    { id: 102, name: 'التكاثر', transliteration: 'At-Takathur', translation: 'The Rivalry in world increase', revelation: 'Meccan', numberOfAyahs: 8, juz: [30], page: 600 },
    { id: 103, name: 'العصر', transliteration: 'Al-\'Asr', translation: 'The Declining Day', revelation: 'Meccan', numberOfAyahs: 3, juz: [30], page: 601 },
    { id: 104, name: 'الهمزة', transliteration: 'Al-Humazah', translation: 'The Traducer', revelation: 'Meccan', numberOfAyahs: 9, juz: [30], page: 601 },
    { id: 105, name: 'الفيل', transliteration: 'Al-Fil', translation: 'The Elephant', revelation: 'Meccan', numberOfAyahs: 5, juz: [30], page: 601 },
    { id: 106, name: 'قريش', transliteration: 'Quraysh', translation: 'Quraysh', revelation: 'Meccan', numberOfAyahs: 4, juz: [30], page: 602 },
    { id: 107, name: 'الماعون', transliteration: 'Al-Ma\'un', translation: 'The Small Kindnesses', revelation: 'Meccan', numberOfAyahs: 7, juz: [30], page: 602 },
    { id: 108, name: 'الكوثر', transliteration: 'Al-Kawthar', translation: 'The Abundance', revelation: 'Meccan', numberOfAyahs: 3, juz: [30], page: 602 },
    { id: 109, name: 'الكافرون', transliteration: 'Al-Kafirun', translation: 'The Disbelievers', revelation: 'Meccan', numberOfAyahs: 6, juz: [30], page: 603 },
    { id: 110, name: 'النصر', transliteration: 'An-Nasr', translation: 'The Divine Support', revelation: 'Medinan', numberOfAyahs: 3, juz: [30], page: 603 },
    { id: 111, name: 'المسد', transliteration: 'Al-Masad', translation: 'The Palm Fiber', revelation: 'Meccan', numberOfAyahs: 5, juz: [30], page: 603 },
    { id: 112, name: 'الإخلاص', transliteration: 'Al-Ikhlas', translation: 'The Sincerity', revelation: 'Meccan', numberOfAyahs: 4, juz: [30], page: 604 },
    { id: 113, name: 'الفلق', transliteration: 'Al-Falaq', translation: 'The Daybreak', revelation: 'Meccan', numberOfAyahs: 5, juz: [30], page: 604 },
    { id: 114, name: 'الناس', transliteration: 'An-Nas', translation: 'Mankind', revelation: 'Meccan', numberOfAyahs: 6, juz: [30], page: 604 },
];

// 30 Juz (Parts) data
export const JUZ_DATA: Juz[] = [
    { id: 1, name: 'Alif Lam Mim', nameArabic: 'آلم', startSurah: 1, startAyah: 1, endSurah: 2, endAyah: 141 },
    { id: 2, name: 'Sayaqul', nameArabic: 'سيقول', startSurah: 2, startAyah: 142, endSurah: 2, endAyah: 252 },
    { id: 3, name: 'Tilka Ar-Rusul', nameArabic: 'تلك الرسل', startSurah: 2, startAyah: 253, endSurah: 3, endAyah: 92 },
    { id: 4, name: 'Lan Tanaloo', nameArabic: 'لن تنالوا', startSurah: 3, startAyah: 93, endSurah: 4, endAyah: 23 },
    { id: 5, name: 'Wal Muhsanat', nameArabic: 'والمحصنات', startSurah: 4, startAyah: 24, endSurah: 4, endAyah: 147 },
    { id: 6, name: 'La Yuhibbu Allah', nameArabic: 'لا يحب الله', startSurah: 4, startAyah: 148, endSurah: 5, endAyah: 81 },
    { id: 7, name: 'Wa Idha Sami\'u', nameArabic: 'وإذا سمعوا', startSurah: 5, startAyah: 82, endSurah: 6, endAyah: 110 },
    { id: 8, name: 'Wa Law Annana', nameArabic: 'ولو أننا', startSurah: 6, startAyah: 111, endSurah: 7, endAyah: 87 },
    { id: 9, name: 'Qal Al-Mala', nameArabic: 'قال الملأ', startSurah: 7, startAyah: 88, endSurah: 8, endAyah: 40 },
    { id: 10, name: 'Wa A\'lamu', nameArabic: 'واعلموا', startSurah: 8, startAyah: 41, endSurah: 9, endAyah: 92 },
    { id: 11, name: 'Ya\'tadhirun', nameArabic: 'يعتذرون', startSurah: 9, startAyah: 93, endSurah: 11, endAyah: 5 },
    { id: 12, name: 'Wa Ma Min Dabbah', nameArabic: 'وما من دابة', startSurah: 11, startAyah: 6, endSurah: 12, endAyah: 52 },
    { id: 13, name: 'Wa Ma Ubarri\'u', nameArabic: 'وما أبرئ', startSurah: 12, startAyah: 53, endSurah: 14, endAyah: 52 },
    { id: 14, name: 'Rubama', nameArabic: 'ربما', startSurah: 15, startAyah: 1, endSurah: 16, endAyah: 128 },
    { id: 15, name: 'Subhana Alladhi', nameArabic: 'سبحان الذي', startSurah: 17, startAyah: 1, endSurah: 18, endAyah: 74 },
    { id: 16, name: 'Qala Alam', nameArabic: 'قال ألم', startSurah: 18, startAyah: 75, endSurah: 20, endAyah: 135 },
    { id: 17, name: 'Iqtaraba', nameArabic: 'اقترب', startSurah: 21, startAyah: 1, endSurah: 22, endAyah: 78 },
    { id: 18, name: 'Qad Aflaha', nameArabic: 'قد أفلح', startSurah: 23, startAyah: 1, endSurah: 25, endAyah: 20 },
    { id: 19, name: 'Wa Qala Alladhina', nameArabic: 'وقال الذين', startSurah: 25, startAyah: 21, endSurah: 27, endAyah: 55 },
    { id: 20, name: 'Amman Khalaqa', nameArabic: 'أمن خلق', startSurah: 27, startAyah: 56, endSurah: 29, endAyah: 45 },
    { id: 21, name: 'Utlu Ma Oohiya', nameArabic: 'اتل ما أوحي', startSurah: 29, startAyah: 46, endSurah: 33, endAyah: 30 },
    { id: 22, name: 'Wa Man Yaqnut', nameArabic: 'ومن يقنت', startSurah: 33, startAyah: 31, endSurah: 36, endAyah: 27 },
    { id: 23, name: 'Wa Mali', nameArabic: 'وما لي', startSurah: 36, startAyah: 28, endSurah: 39, endAyah: 31 },
    { id: 24, name: 'Fa Man Azlam', nameArabic: 'فمن أظلم', startSurah: 39, startAyah: 32, endSurah: 41, endAyah: 46 },
    { id: 25, name: 'Ilayhi Yurad', nameArabic: 'إليه يرد', startSurah: 41, startAyah: 47, endSurah: 45, endAyah: 37 },
    { id: 26, name: 'Ha Mim', nameArabic: 'حم', startSurah: 46, startAyah: 1, endSurah: 51, endAyah: 30 },
    { id: 27, name: 'Qala Fa Ma Khatbukum', nameArabic: 'قال فما خطبكم', startSurah: 51, startAyah: 31, endSurah: 57, endAyah: 29 },
    { id: 28, name: 'Qad Sami\'a Allah', nameArabic: 'قد سمع الله', startSurah: 58, startAyah: 1, endSurah: 66, endAyah: 12 },
    { id: 29, name: 'Tabarak Alladhi', nameArabic: 'تبارك الذي', startSurah: 67, startAyah: 1, endSurah: 77, endAyah: 50 },
    { id: 30, name: 'Amma', nameArabic: 'عم', startSurah: 78, startAyah: 1, endSurah: 114, endAyah: 6 },
];

// Helper function to get Surah by ID
export const getSurahById = (id: number): Surah | undefined => {
    return SURAHS.find(surah => surah.id === id);
};

// Helper function to get Juz by ID
export const getJuzById = (id: number): Juz | undefined => {
    return JUZ_DATA.find(juz => juz.id === id);
};

// Helper function to get Surahs in a Juz
export const getSurahsInJuz = (juzId: number): Surah[] => {
    return SURAHS.filter(surah => surah.juz.includes(juzId));
};

// Bismillah text
export const BISMILLAH = 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ';
export const BISMILLAH_TRANSLATION = 'In the name of Allah, the Most Gracious, the Most Merciful';
